# Generated by Django 2.2.2 on 2020-10-08 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compaign_name', models.CharField(blank=True, max_length=250, null=True)),
                ('linkedin_id', models.CharField(blank=True, max_length=250, null=True)),
                ('count', models.CharField(blank=True, max_length=250, null=True)),
                ('linkedin_url', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Campaign',
                'verbose_name_plural': 'Campaign',
            },
        ),
        migrations.CreateModel(
            name='SendindUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mini_profile', models.CharField(blank=True, max_length=250, null=True)),
                ('seen', models.BooleanField(default=False)),
                ('connect', models.BooleanField(default=False)),
                ('message', models.BooleanField(default=False)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='campaign.Campaign')),
            ],
            options={
                'verbose_name': 'SendindUser',
                'verbose_name_plural': 'SendindUsers',
            },
        ),
    ]
