# Generated by Django 2.2.2 on 2020-10-09 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0003_sendinduser_linkedin_user_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='message_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
