# Generated by Django 2.2.2 on 2020-10-13 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0004_campaign_message_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='campaign_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
